# Generated by Django 6.0.6 on 2026-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Payoneer', 'Payoneer')], max_length=20, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_type', models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Payoneer', 'Payoneer')], default='MTN Mobile Money', max_length=20)),
                ('momo_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payoneer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payoneer_payee_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
