# Generated by Django 6.0.6 on 2026-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='momo_phone_number',
        ),
        migrations.AddField(
            model_name='wallet',
            name='paystack_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paystack', 'Paystack'), ('Payoneer', 'Payoneer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Payoneer', 'Payoneer')], default='Paystack', max_length=20),
        ),
    ]
