# Generated by Django 6.0.6 on 2026-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_farm_latitude_farm_longitude_order_deliver_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='RETAIL', max_length=20),
        ),
    ]
