# Generated by Django 6.0.6 on 2026-07-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_order_type'),
        ('users', '0002_alter_farmer_options_alter_baseuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional note from the farmer', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_received', to='users.driver')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_sent', to='users.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('farmer', 'driver')},
            },
        ),
    ]
