# Generated by Django 6.0.6 on 2026-07-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_hire_request'),
        ('users', '0002_alter_farmer_options_alter_baseuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.farmer'),
        ),
    ]
