# Generated by Django 6.0.6 on 2026-07-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_farmproduct_farm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmproduct',
            old_name='farm',
            new_name='farmer',
        ),
    ]
