# Generated by Django 6.0.6 on 2026-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_rename_farm_farmproduct_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
