# Generated by Django 6.0.6 on 2026-07-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'permissions': [('CAN_CREATE_PRODUCTS', 'Can create products'), ('CAN_MANAGE_ORDERS', 'Can manage orders'), ('CAN_VIEW_DELIVERY_STATUS', 'Can view delivery status'), ('CAN_CREATE_POSTS', 'Can create posts')]},
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
